### ISSUE TITLE
Unable to run grunt selenium with described options

### ISSUE THREAD

**Issue by cstewart87** [sideroad/grunt-selenium#1]
Using the explained options in the README (using my own path to the test suite) I am unable to successfully run grunt selenium.  I've attached a sample debug run.  I also receive the same error when running your example test suite.

Running "selenium:suite" (selenium) task
[D] Task source: /Users/curtstewart/Git/GitHub/Work/StackStudio/node_modules/grunt-selenium/tasks/selenium.js
[D] Setup Selenium Server...

> > Mar 19, 2013 8:32:41 AM org.openqa.grid.selenium.GridLauncher main
> > INFO: Launching a standalone server
> > [D] 08:32:41.336 INFO - Java: Apple Inc. 20.14-b01-447
> > [D] 08:32:41.337 INFO - OS: Mac OS X 10.8.3 x86_64
> > [D] 08:32:41.345 INFO - v2.31.0, with Core v2.31.0. Built from revision 1bd294d
> > [D] 08:32:41.425 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
> > [D] 08:32:41.426 INFO - Version Jetty/5.1.x
> > [D] 08:32:41.426 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
> > [D] 08:32:41.427 INFO - Started HttpContext[/selenium-server,/selenium-server]
> > [D] 08:32:41.427 INFO - Started HttpContext[/,/]
> > [D] 08:32:41.456 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@77f297e7
> > [D] 08:32:41.456 INFO - Started HttpContext[/wd,/wd]
> > [D] 08:32:41.460 INFO - Started SocketListener on 0.0.0.0:4444
> > [D] 08:32:41.460 INFO - Started org.openqa.jetty.jetty.Server@3934f69a
> > Setup browser [firefox]
> > Fatal error: Cannot call method 'forEach' of undefined

**Comment by sideroad** [comment]
Could you tell me below?
- Gruntfile.js contents
- Node version
- Grunt version( 0.4.0 or 0.4.1 )

**Comment by cstewart87** [comment]
-  **Node version:**
  v0.8.16
- **Grunt version:** 
  grunt-cli v0.1.6
  grunt v0.4.0rc4
-  **Gruntfile.js Contents:**

``` javascript
/*jshint smarttabs:true */
/*global module:false require:true*/
module.exports = function(grunt) {

  // Project configuration.
    grunt.initConfig({
     selenium: {
        options: {
            browsers: ['firefox']
        },
        suite: {
            files: {
                'example': ['test/*.suite']
            }
        }
    }
  });
  grunt.loadNpmTasks('grunt-selenium');
};
```

**Comment by sideroad** [comment]
Same error occurred in grunt v0.4.0rc4.
Could you update to grunt 0.4.0 or 0.4.1?

**Comment by cstewart87** [comment]
Looks like the update to grunt v0.4.1 allowed me to get through that issue, thanks!

My test suite is still not completing though.  Does grunt-selenium only support certain commands?  The output pasted below is telling me that some of our test commands are not supported.  The rest of the errors may be caused by my environment or test suite, not grunt-selenium itself.

Running "selenium:suite" (selenium) task

> > Mar 20, 2013 8:34:31 AM org.openqa.grid.selenium.GridLauncher main
> > INFO: Launching a standalone server
> > Setup browser [firefox]
> >   Running suite[test/StackStudio_Tests.suite]
> > Command not supported[waitForElementPresent]
> > Command not supported[waitForElementPresent]
> > Command not supported[verifyText]
> > Command not supported[waitForElementPresent]
> > Command not supported[waitForElementPresent]
> > Command not supported[type]
> > Command not supported[type]
> > Command not supported[waitForElementPresent]
> > Command not supported[waitForElementPresent]
> > Command not supported[verifyText]
> > Command not supported[verifyText]
> > Command not supported[verifyText]
> > ..........
> > ..........
> > ..........
> >     Running test case[StackStudio Navigation (Light)]
> > 08:34:35.768 WARN - Exception thrown
> > org.openqa.selenium.WebDriverException: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]
> > Command duration or timeout: 6 milliseconds
> > Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
> > System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_43'
> > Session ID: 895876a2-7307-794e-b7c7-cce8fa7448cf
> > Driver info: org.openqa.selenium.firefox.FirefoxDriver
> > Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=firefox, rotatable=false, locationContextEnabled=true, version=18.0.1, cssSelectorsEnabled=true, databaseEnabled=true, handlesAlerts=true, browserConnectionEnabled=true, nativeEvents=false, webStorageEnabled=true, applicationCacheEnabled=true, takesScreenshot=true}]
> >  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> >  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
> >  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
> >  at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
> >  at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:187)
> >  at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
> >  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
> >  at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:276)
> >  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> >  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
> >  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
> >  at java.lang.reflect.Method.invoke(Method.java:597)
> >  at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
> >  at com.sun.proxy.$Proxy1.get(Unknown Source)
> >  at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:155)
> >  at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:38)
> >  at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:1)
> >  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
> >  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
> >  at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
> >  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
> >  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
> >  at java.lang.Thread.run(Thread.java:680)
> > Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]
> > Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
> > System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_43'
> > Driver info: driver.version: unknown
> > 08:34:35.772 WARN - Exception: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]
> > Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
> > System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_43'
> > Driver info: driver.version: unknown

**Comment by sideroad** [comment]
Currently, this plugin support a little compatibility.
But I'll develop to expand compatible.
I will support below prior to other command.
waitForElementPresent, verifyText , type
