### ISSUE TITLE
Sample tests?

### ISSUE THREAD

**Issue by psyked** [sideroad/grunt-selenium#22]
I'm trying to use this plugin with some tests that I've recorded in the Firefox Selenium IDE, but I can't get them to work with this task.  I don't think the tests are at fault, although I can't be sure about that.  

Do you have any example test cases that I can use to validate that the tasks actually run correctly on my machine? All I'm getting is the browser open, then everything stops on a blank page and never actually runs my test suite.

**Comment by sideroad** [comment]
hi
thanks for consider to use this plugin.
Could you tell me about your environment in more detail? ( OS, Browser, )

and also, could you try to execute sample for test case?
1. Download or git clone grunt-selenium
2. `npm install .`
3. `grunt selenium`
