### ISSUE TITLE
What is "safe mode" in IE

### ISSUE THREAD

**Issue by enriquemorenotent** [sideroad/grunt-selenium#23]
In the instructions said:

"Check Safe mode on all site type"

Whatis this? Is this the same as running Windows in "Safe Mode"?

**Comment by sideroad** [comment]
sorry, I'm wrong. please check "Enable Protect Mode"  as explained detail below

http://nashibukasan.blogspot.jp/2012/11/ie-protected-mode-and-selenium.html?m=1

**Comment by enriquemorenotent** [comment]
Thanks! :+1: 

Dont forget to correct the documentation :)
