### ISSUE TITLE
Environment Requirements

### ISSUE THREAD

**Issue by cstewart87** [sideroad/grunt-selenium#6]
Has this been tested in any particular environment?  I can't appear to successfully run your tests in mine.

I believe my environment info is in the output below, but here it is again:
- Mac OS X 10.8 x86_64
- grunt version
  - grunt-cli v0.1.6
  - grunt v0.4.0
- node version
  - v0.8.16
- java version
  - 1.6.0_43

> > Setup browser [chrome]
> > Running suite[test/source/example1.suite]
> > 08:18:46.858 WARN - Exception thrown
> > java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
> > Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
> > System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_43'
> > Driver info: driver.version: unknown
> >  at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
> >  at java.util.concurrent.FutureTask.get(FutureTask.java:83)
> >  at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:176)
> >  at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:112)
> >  at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:89)
> >  at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:89)
> >  at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:63)
> >  at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:201)
> >  at org.openqa.selenium.remote.server.JsonHttpRemoteConfig.handleRequest(JsonHttpRemoteConfig.java:192)
> >  at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
> >  at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:167)
> >  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
> >  at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:139)
> >  at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
> >  at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
> >  at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:677)
> >  at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
> >  at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
> >  at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
> >  at org.openqa.jetty.http.HttpServer.service(HttpServer.java:914)
> >  at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
> >  at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
> >  at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
> >  at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
> >  at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
> >  at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
> > Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
> > Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
> > System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_43'
> > Driver info: driver.version: unknown
> >  at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:67)
> >  at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:51)
> >  at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:215)
> >  at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
> >  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
> >  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
> >  at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
> >  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
> >  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
> >  at java.lang.Thread.run(Thread.java:680)
> > Caused by: java.lang.reflect.InvocationTargetException
> >  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> >  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
> >  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
> >  at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
> >  at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:57)
> >  ... 9 more
> > Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://code.google.com/p/chromedriver/downloads/list
> >  at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
> >  at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:105)
> >  at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:75)
> >  at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:129)
> >  ... 14 more
> > 08:18:46.862 WARN - Exception: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://code.google.com/p/chromedriver/downloads/list

**Comment by sideroad** [comment]
Did you install chrome driver?
and could you confirm to set path to chrome driver in PATH system property?
